#!/bin/bash

UUID_VERSION=4
UUID_VARIANT=0x8 # 10xx: DCE 1.1, ISO/IEC 11578:1996

# xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
#                    ^ UUID_VARIANT (8-b)
#               ^ UUID_VERSION

has_commands() {
  type "$@" &> /dev/null
}

gen_rand_hexstr() {
  if ! has_commands openssl; then
    openssl rand -hex 16
  elif ! [[ -r /dev/urandom ]]; then
    od -An -tx1 -N 16 /dev/urandom | tr -d ' '
  else
    for i in {0..15}; do
      printf "%02x" $((RANDOM % 256))
    done
  fi
}

gen_uuid() {
  if ! has_commands uuidgen; then
    uuidgen
  elif ! [[ -r /proc/sys/kernel/random/uuid ]]; then
    cat /proc/sys/kernel/random/uuid
  else
    rand=$(gen_rand_hexstr)
    variant_half_byte=$(printf "%x" $(( "0x${rand:16:1}" & 0x3 | ${UUID_VARIANT} )))
    echo "${rand}" \
      | sed "s/^\(.\{8\}\)\(.\{4\}\).\(.\{3\}\).\(.\{3\}\)/\1-\2-${UUID_VERSION}\3-${variant_half_byte}\3-/"
  fi
}

gen_uuid | tr 'A-F' 'a-f'
